### ISSUE TITLE
mediaService

### ISSUE THREAD

**Issue by salt42** [Fryday80/SRzA#139]
ich muss die rechte auch anpassen. wenn dir langweilig ist kannst du mal alle folder.configs anpassen.
```
[Permissions]
folderRead[]        ; deprecated
folderWrite[]       ; deprecated
allRead[]              ; deprecated
allWrite[]             ; deprecated
read[]                  ; new
write[]                 ; new


[FileRestrictions]       ; deprecated

[Restrictions]            ; new
AdministratorRead[] = "doctor.jpg"      ; wie es in FileRestrictions war nur jetzt auch mir ordnern
```

### info:
- die rechte greifen für alles was im selben order wie die "folder.conf" ist. aber nicht auf den ordner in dem sie sich befindet
- rolle "Administrator" umgeht den file permission check. will heißen in den folder.conf's braucht man administrator nicht mehr eintragen.

### todo
- [x] multiUpload ausprobieren (sowas dachte ich in einem upload plugin [mediaService:651] )
- [x] kleine thumb cleanup funktion. die alle thumbs löscht die kein original mehr haben.
- [ ] kleine thumb restore funktion die thumbs erstellt wenn sie fehlen.

**Comment by Fryday80** [comment]
important!!
implement filename <-> thumbs names converter
- [ ]
